[package]
name = "SmARTR"
version = "0.1.0"
edition = "2021"
authors = ["mitm"]

[dependencies]
bincode = "1.3.3"
clap = { version = "4.1.4", features = ["derive"] }
cpal = "0.15.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
