[package]
name = "SmARTR"
version = "0.1.0"
edition = "2021"
authors = ["mitm"]

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
rodio = "0.16.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
